### ISSUE TITLE
Iguana Tweaks Integration Issues

### ISSUE THREAD

**Issue by coshne** [Almagnus1/IaconClient#1]
iguana mods needs to allow flint pickaxes to properly mine copper

**Comment by Almagnus1** [comment]
I've been looking into this, and what the current configuration of IguanaTweaks does is force you to level up the flint pickaxe to get a mining level +1, and then you'll be able to mine copper.  That will take ~200 blocks mined to do that, which can be done if you 

The other thing I've seen is that it forces Tinker's to be the first thing done, and not having access to clay nearby (which should be in any major body of water, going by what I've seen thus far) is going to a pain point.

For the smeltery, if you get a stack of gravel, sand, and clay, you can make the 4x4x2 smeltery (smallest possible with a 2x2x1 interior), and that's enough to get you going.  Once you have either found gold or aluminum, that will allow you to make the casts, which will let you progress from there.  Be aware that whatever you use for the cast will likely be consumed in the process of making the cast.  (As an FYI, you can smelt cobble to get the seared brick needed to expand the smeltery).

All that said, I can see situations where needing a wooden and stone pickaxe are necessary.

Maybe revisit this again in Beta once we have a Iacon rolled over to the modpack?

**Comment by Entity325** [comment]
Flint picks mine copper once they have leveled enough to get a mining boost. After a part upgrade, the pick will "remember" its mining level increases after a couple dozen blocks.

Magma can be acquired in Iguana Tweaks using the clay bucket, which is made using 3 clay balls and then cooked in a furnace.

Allowing vanilla stone picks to mine copper, or re-enabling stone as a legal tool material in Iguana and setting its mining level to Copper would probably help flatten the curve here a bit.

**Comment by Almagnus1** [comment]
After coming off of a playtest session, I see pain points early on and stepping through the nether.

For the early on point, I'm thinking of just re-enabling the vanilla wood and stone picks, set to mine stone and copper respectively, which should get the player rolling.  If a player's in an area where clay is scarce (or non-existent), they need SOME way to get going, or life's gonna really suck.

The top end, the bronze pickaxe needs to be bumped up a level, so that a bronze tool can mine obsidian.  Having the player be forced to add a diamond to a bronze tool is esoteric, and I don't like how that plays.

Remaining balance questions:
Should stone be at mining level iron?
Should a weaker version of the vanilla iron pick with mining level tin be added?

**Comment by Entity325** [comment]
I believe copper itself is only mining level copper. Each material should for sure grant access to at least one material level above it.

With the re-addition of wood and stone Vanilla tools, stone is actually easier to get than flint. To this end, I am of the opinion that vanilla stone and TC flint tools should have the same mining levels.

I do agree with making iron tools Tin-level, as TC+Iguana basically puts tin and bronze between iron and diamond.

**Comment by Almagnus1** [comment]
So here's where I'm standing with this atm:
I can selectively nerf any vanilla tool and assign them whatever mining level I want.

My thinking is wood => stone => copper => iron(?), which would give you inferior tools, but potentially give you good reach.  Iron is up in the air atm though.

What I'm getting caught up on, however, is selectively enabling the Thermal Foundation tools, as I can't figure out the right string in the man.cfg for Iguana Tweaks configs to explicitly nerf  most of the Thermal Foundation tools.  For all practical purposes, it means the only shovel you get is the wooden one, you get a choice of wooden or stone axes, and you have the wood and stone pickaxe.

The real concern is if you get screwed with world gen and don't have access to sand, clay, and/or gravel then you're done, because you can't make a smeltery to cast the copper (or higher) components.

And if you can't make a smeltery, then you have no access to iron, as without iron, you can't advance in Botania and you can't start Thaumcraft.  I really don't like that issue with the early game.

Either way, I'm gonna commit what I have with the Iguana Tweaks thus far if someone else wants to wail on it for a bit.

**Comment by Almagnus1** [comment]
And another update:

I got the copper pick back in the game so there's a path to iron in case you are horribly screwed with terrain (or just want to ignore Tinker's Construct and head straight into Thaumcraft or Botania).

To summarize where we are with the issue:

You should be able to do the following pick upgrade:

Wood => Stone => Copper => <mods tools>

Botania's picks have been configured to go from Redstone => Obsidian => Ardite (which is actually a nerf on the mana steel pickaxe once it was reneabled).  Also, all of the manasteel tools have been un-nerfed as they rely upon mana generation.  I am sorely tempted to turn back on flower degradation for the day/night passive flowers and hydrangeas to compensate (FYI: it doesn't affect the better mana producing flowers).

What it does do is open it up so a player can focus solely on magic and ignore the tech side of things if that's what they really want to do, as both Botania and Thaumcraft need iron before you can start working with the mod.

So we have a fuller kit of vanilla tools, the following have also been reenabled:
Wood Shovel, Wood Axe, Stone Shovel, Stone Axe

While the axes are general quality of life (as you will quickly be able to make better tools), the shovels may be useful initially for getting smelteries going.  That may be something to revisit at a later point in time.

As far as the copper pickaxe goes, it's naturally got around 10% more durability than the stone pickaxe, which seems fine by me.

We'll circle back to the iron pickaxe later on, but I don't think that's necessary given the array of tools you can get to with the magic mods, and also with the tinker's stuff.

As an FYI, all hoes, swords, and other tools are unaffected by Iguana tweaks - and there's no point to it as the Tinker's sword is probably the best in the current pack once it's leveled to 6 with a good build.
